/** UI strings for ClubPublicPage */

export const CLUB_PUBLIC_TRANSLATIONS = {
    en: {
      backToHome: 'Back to home',
      aboutClub: 'About the club',
      facilities: 'Facilities & courts',
      courtsCount: 'Courts',
      offers: 'Current offers',
      offersFromAdmin: 'Offers from the club',
      contact: 'Contact',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      website: 'Website',
      joinClub: 'Join this club',
      joinSuccess: 'You have joined the club successfully.',
      alreadyMember: 'You are already a member of this club.',
      registerFirst: 'Register on the platform first',
      registerMembers: 'Register as member',
      loginPlatform: 'Login with PlayTix',
      registerThenJoin: 'You must register on PlayTix before joining a club. Register now, then return here to join.',
      tournaments: 'Tournaments',
      matches: 'Matches',
      members: 'Members',
      bookingsTable: 'Upcoming bookings',
      bookingsEmpty: 'No upcoming court bookings.',
      date: 'Date',
      time: 'Time',
      court: 'Court',
      customer: 'Customer',
      currentTournaments: 'Tournaments today',
      currentTournamentsEmpty: 'No tournaments scheduled for today.',
      futureTournaments: 'Upcoming tournaments',
      futureTournamentsEmpty: 'No upcoming tournaments scheduled.',
      futureTournamentsOpen: 'Upcoming — open registration',
      futureTournamentsOpenHint: 'No members assigned to teams yet.',
      futureTournamentsWithTeams: 'Upcoming — teams registered',
      kingOfCourt: 'King of the Court',
      socialTournament: 'Social Tournament',
      validUntil: 'Valid until',
      discount: 'off',
      storeTitle: 'Store',
      storeEmpty: 'No products in the store yet.',
      uncategorized: 'Other',
      sale: 'Sale',
      viewProduct: 'View',
      inStock: 'In stock',
      outOfStock: 'Out of stock',
      courtBooking: 'Court booking',
      selectDate: 'Select date',
      available: 'Available',
      booked: 'Booked',
      tournamentBooked: 'Tournament (King of the Court)',
      tournamentBookedSocial: 'Tournament (Social)',
      bookNow: 'Book now',
      bookingPrice: 'Price',
      confirmBooking: 'Confirm booking',
      bookingSuccess: 'Booking confirmed!',
      paymentStyle: 'Payment style',
      paymentStyleDesc: 'Who pays for this booking?',
      iPay: 'I pay',
      iPayDesc: 'I pay the full amount',
      splitWithOthers: 'Split with others',
      splitWithOthersDesc: 'Share the cost with other members',
      splitStepParticipantsTitle: 'Who is sharing?',
      splitStepParticipantsDesc: 'Add each person first. You can type a number or pick one contact at a time — same screen for both.',
      splitStepAmountsTitle: 'Split amounts',
      splitStepAmountsDesc: 'Share payment links after confirming amounts. Your share is calculated automatically.',
      paymentMethod: 'Payment method',
      paymentMethodDesc: 'How do you pay?',
      payAtClub: 'Cash at club',
      payAtClubDesc: 'Pay with cash or card at the club',
      creditCard: 'Credit card (pay now)',
      mada: 'Mada (pay now)',
      electronicPayment: 'Electronic payment',
      payFromWallet: 'Pay from my wallet',
      walletAvailable: 'Available balance',
      walletBalanceLoading: 'Loading balance…',
      walletBalanceError: 'Could not load balance.',
      walletRemainderHint: 'Your wallet balance will be applied first. Pay the remaining {remainder} {currency} using one of the methods below.',
      walletRemainderTitle: 'Pay the remainder',
      walletRemainderWhileLoading: 'Your wallet will be charged first. If it does not cover the full price, you will complete the rest with the method you choose below.',
      walletRemainderUnknownBalance: 'Your wallet will be charged first (up to your balance). Pay any remainder using one of the methods below.',
      viewMyBookings: 'View my bookings',
      splitInviteBannerTitle: 'Invite guests to pay',
      splitInviteBannerIntro:
        'Each link is personal. Send it by WhatsApp so guests can sign up (if needed), join this club, and complete payment.',
      splitInviteGuest: 'Guest',
      splitInviteShare: 'Send',
      splitInviteDismiss: 'Dismiss',
      splitInviteEditPhone: 'Edit number',
      splitInviteSave: 'Save',
      splitInviteCancel: 'Cancel',
      splitInviteRemoveGuest: 'Remove',
      splitInviteConfirmRemove: 'Remove this guest from the split? They have not paid yet.',
      splitInvitePhoneLabel: 'Mobile',
      splitInviteUpdateError: 'Could not update. Check the number and try again.',
      splitInviteRemoveError: 'Could not remove. Try again.',
      loginToBook: 'Login to book courts',
      courtPrices: 'Court booking prices',
      duration: 'Duration',
      price: 'Price',
      joinPromptTitle: 'You\'re one step away!',
      joinPromptText: 'Join this club now to book courts, participate in tournaments, and enjoy member benefits.',
      joinPreviouslyMemberHint: 'Previously a member? Refresh the page or ask the club to re-add you.',
      profileIncompleteText: 'Please complete your member registration details (profile, phone if needed, password) from your account.',
      profileIncompleteCta: 'Complete profile',
      joinTraining: 'Join training',
      joinTrainingPrice: 'Price (one slot)',
      totalPrice: 'Total price',
      trainingSessionsLabel: 'Training sessions',
      trainingPayAtClub: 'Pay at club',
      trainingPayDirect: 'Direct payment',
      trainingPaySplit: 'Share with others',
      trainingPayFull: 'Pay full amount',
      confirmJoinTraining: 'Confirm join',
      legendCourt: 'Court booking',
      legendCoach: 'Coach session',
      legendTournament: 'Tournament',
      schedulePrevDay: 'Previous day',
      scheduleNextDay: 'Next day',
      continueBooking: 'Continue',
      back: 'Back',
      trainingJoinCompletePayment: 'Complete payment',
      trainingJoinPaymentMethodStep: 'How would you like to pay?',
      trainingJoinMaxSplitHint: 'You can invite up to {n} people to share payment (coach limit for this session).',
    },
    ar: {
      backToHome: 'العودة للرئيسية',
      aboutClub: 'عن النادي',
      facilities: 'المرافق والملاعب',
      courtsCount: 'ملاعب',
      offers: 'العروض الحالية',
      offersFromAdmin: 'عروض النادي',
      contact: 'التواصل',
      address: 'العنوان',
      phone: 'الهاتف',
      email: 'البريد الإلكتروني',
      website: 'الموقع',
      joinClub: 'التسجيل كعضو في النادي',
      joinSuccess: 'تم انضمامك للنادي بنجاح.',
      alreadyMember: 'أنت عضو في هذا النادي مسبقاً.',
      registerFirst: 'سجّل في PlayTix أولاً',
      registerMembers: 'تسجيل الأعضاء',
      loginPlatform: 'تسجيل الدخول بحساب PlayTix',
      registerThenJoin: 'يجب التسجيل في PlayTix قبل الانضمام لأي نادي. سجّل الآن ثم عد هنا للانضمام.',
      tournaments: 'بطولات',
      matches: 'مباريات',
      members: 'أعضاء',
      bookingsTable: 'جدول الحجوزات القادمة',
      bookingsEmpty: 'لا توجد حجوزات ملاعب قادمة.',
      date: 'التاريخ',
      time: 'الوقت',
      court: 'الملعب',
      customer: 'العميل',
      currentTournaments: 'البطولات المقامة اليوم',
      currentTournamentsEmpty: 'لا توجد بطولات مجدولة لليوم.',
      futureTournaments: 'البطولات المجدولة القادمة',
      futureTournamentsEmpty: 'لا توجد بطولات مجدولة قادمة.',
      futureTournamentsOpen: 'قادمة — التسجيل مفتوح',
      futureTournamentsOpenHint: 'لم يُعيَّن أعضاء في الفرق بعد.',
      futureTournamentsWithTeams: 'قادمة — فرق مسجّلة',
      teamsRegisteredShort: 'الفرق',
      membersTotalShort: 'الأعضاء',
      membersInTeam: 'أعضاء',
      teamRosterTitle: 'الفرق والأعضاء',
      kingOfCourt: 'ملك الملعب',
      socialTournament: 'بطولة سوشيال',
      validUntil: 'صالح حتى',
      discount: 'خصم',
      storeTitle: 'المتجر',
      storeEmpty: 'لا توجد منتجات في المتجر بعد.',
      uncategorized: 'أخرى',
      sale: 'خصم',
      viewProduct: 'عرض',
      inStock: 'متوفر',
      outOfStock: 'غير متوفر',
      courtBooking: 'حجز الملاعب',
      selectDate: 'اختر التاريخ',
      available: 'متاح',
      booked: 'محجوز',
      tournamentBooked: 'بطولة (ملك الملعب)',
      tournamentBookedSocial: 'بطولة (سوشيال)',
      bookNow: 'احجز الآن',
      bookingPrice: 'السعر',
      confirmBooking: 'تأكيد الحجز',
      bookingSuccess: 'تم تأكيد الحجز!',
      paymentStyle: 'أسلوب الدفع',
      paymentStyleDesc: 'من يدفع ثمن هذا الحجز؟',
      iPay: 'أنا أدفع',
      iPayDesc: 'أدفع المبلغ كاملاً',
      splitWithOthers: 'أشارك الدفع مع آخرين',
      splitWithOthersDesc: 'تقسيم التكلفة مع أعضاء آخرين',
      splitStepParticipantsTitle: 'من يشارك معك؟',
      splitStepParticipantsDesc: 'أضف كل شخص أولاً. يمكنك كتابة الرقم أو اختيار جهة اتصال واحدة في المرة — نفس الشاشة للطريقتين.',
      splitStepAmountsTitle: 'تقسيم المبالغ',
      splitStepAmountsDesc: 'أرسل روابط الدفع بعد ضبط المبالغ. تُحسب حصتك تلقائياً.',
      paymentMethod: 'طريقة الدفع',
      paymentMethodDesc: 'كيف تدفع؟',
      payAtClub: 'كاش في النادي',
      payAtClubDesc: 'الدفع نقداً أو بالبطاقة في النادي',
      creditCard: 'البطاقة الائتمانية (ادفع الآن)',
      mada: 'متاب (ادفع الآن)',
      electronicPayment: 'الدفع الإلكتروني',
      payFromWallet: 'الدفع من محفظتي',
      walletAvailable: 'الرصيد المتاح',
      walletBalanceLoading: 'جاري تحميل الرصيد…',
      walletBalanceError: 'تعذّر تحميل الرصيد.',
      walletRemainderHint: 'سيُخصم أولاً من رصيد محفظتك. أكمِل المتبقي {remainder} {currency} بإحدى الطرق أدناه.',
      walletRemainderTitle: 'دفع المتبقي',
      walletRemainderWhileLoading: 'سيُخصم أولاً من المحفظة. إن لم يغطِ الرصيد كامل المبلغ، تُكمِل المتبقي بالطريقة التي تختارها أدناه.',
      walletRemainderUnknownBalance: 'سيُخصم أولاً من المحفظة بقدر الرصيد. أكمِل أي متبقي بإحدى الطرق أدناه.',
      viewMyBookings: 'عرض حجوزاتي',
      splitInviteBannerTitle: 'دعوة الضيوف للدفع',
      splitInviteBannerIntro:
        'كل رابط شخصي. أرسله عبر واتساب ليتمكن الضيف من التسجيل إن لزم، والانضمام للنادي، واستكمال الدفع.',
      splitInviteGuest: 'ضيف',
      splitInviteShare: 'واتساب',
      splitInviteDismiss: 'إغلاق',
      splitInviteEditPhone: 'تعديل الرقم',
      splitInviteSave: 'حفظ',
      splitInviteCancel: 'إلغاء',
      splitInviteRemoveGuest: 'حذف',
      splitInviteConfirmRemove: 'إزالة هذا الضيف من التنسيق؟ لم يكتمل دفعه بعد.',
      splitInvitePhoneLabel: 'رقم الجوال',
      splitInviteUpdateError: 'تعذر التحديث. تحقق من الرقم وحاول مرة أخرى.',
      splitInviteRemoveError: 'تعذر الحذف. حاول مرة أخرى.',
      loginToBook: 'سجّل الدخول لحجز الملاعب',
      courtPrices: 'أسعار حجوزات الملاعب',
      duration: 'المدة',
      price: 'السعر',
      joinPromptTitle: 'أنت على بُعد خطوة واحدة!',
      joinPromptText: 'انضم للنادي الآن لحجز الملاعب والمشاركة في البطولات والاستفادة من مزايا العضوية.',
      joinPreviouslyMemberHint: 'كنت عضواً سابقاً؟ حدّث الصفحة أو اطلب من إدارة النادي إعادة ربط العضوية.',
      profileIncompleteText: 'يرجى استكمال بيانات تسجيل العضو (الملف، الجوال إن لزم، كلمة المرور) من حسابك أعلاه.',
      profileIncompleteCta: 'استكمال البيانات',
      joinTraining: 'انضم للتدريب',
      joinTrainingPrice: 'السعر (حصة واحدة)',
      totalPrice: 'الإجمالي',
      trainingSessionsLabel: 'حصص تدريب',
      trainingPayAtClub: 'الدفع في النادي',
      trainingPayDirect: 'الدفع مباشرة',
      trainingPaySplit: 'المشاركة مع أعضاء آخرين',
      trainingPayFull: 'الدفع كامل المبلغ',
      confirmJoinTraining: 'تأكيد الانضمام',
      legendCourt: 'حجز ملعب',
      legendCoach: 'حصة مدرب',
      legendTournament: 'بطولة',
      schedulePrevDay: 'اليوم السابق',
      scheduleNextDay: 'اليوم التالي',
      continueBooking: 'متابعة',
      back: 'رجوع',
      trainingJoinCompletePayment: 'استكمال الدفع',
      trainingJoinPaymentMethodStep: 'كيف تودُّ الدفع؟',
      trainingJoinMaxSplitHint: 'يمكنك إضافة حتى {n} مشاركاً للتقسيم (الحد الذي حدّده المدرب لهذه الحصة).',
    }
  }
