# PlayTix: build transfer zip + combined SQL into folder "copy of project" (Arabic name, UTF-16-safe in script).
# Run from repo root:  powershell -File scripts/build-transfer-pack.ps1

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $root

# "نسخة من المشروع" without non-ASCII bytes in this .ps1 file (avoids OEM codepage parse errors)
$packDirName = [string][char]0x0646 + [char]0x0633 + [char]0x062E + [char]0x0629 + ' ' + [char]0x0645 + [char]0x0646 + ' ' +
  [char]0x0627 + [char]0x0644 + [char]0x0645 + [char]0x0634 + [char]0x0631 + [char]0x0648 + [char]0x0639
$packDir = Join-Path $root $packDirName
if (-not (Test-Path $packDir)) {
  New-Item -ItemType Directory -Path $packDir | Out-Null
}

$createAll = Join-Path $root 'server\db\CREATE_ALL_TABLES.sql'
$syncExtra = Join-Path $root 'server\db\migrations\phpmyadmin-create-missing-tables-and-columns.sql'
$plantGuideSrc = Join-Path $root 'server\db\PLANT_DATABASE.sql'
$combinedOut = Join-Path $packDir 'PLANT_DATABASE_COMBINED.sql'
$plantGuideDest = Join-Path $packDir 'PLANT_DATABASE.sql'

if (-not (Test-Path $createAll)) { throw "Missing: $createAll" }
if (-not (Test-Path $syncExtra)) { throw "Missing: $syncExtra" }

$banner = @"
-- ============================================================================
-- PlayTix PLANT_DATABASE_COMBINED.sql (generated; do not edit by hand)
-- Part 1: CREATE_ALL_TABLES.sql | Part 2: phpmyadmin-create-missing-tables-and-columns.sql
-- After import: set DATABASE_URL and run npm install on the target machine.
-- Generated by: scripts/build-transfer-pack.ps1
-- ============================================================================

"@

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($combinedOut, $banner, $utf8NoBom)
Add-Content -Path $combinedOut -Value (Get-Content -Path $createAll -Raw -Encoding UTF8)
Add-Content -Path $combinedOut -Value "`n`n-- ============ End part 1 / begin part 2 migrations ============`n`n"
Add-Content -Path $combinedOut -Value (Get-Content -Path $syncExtra -Raw -Encoding UTF8)

Copy-Item -Path $plantGuideSrc -Destination $plantGuideDest -Force

Write-Host "Wrote: $combinedOut"
Write-Host "Copied: $plantGuideDest"

$zipName = 'playtix-full-project-transfer.zip'
$zipPath = Join-Path $packDir $zipName
if (Test-Path $zipPath) { Remove-Item -LiteralPath $zipPath -Force }

# tar.exe on Windows often fails with non-ASCII paths; write to TEMP then move.
$zipTemp = Join-Path $env:TEMP ("playtix-transfer-" + [Guid]::NewGuid().ToString("n") + ".zip")
if (Test-Path $zipTemp) { Remove-Item -LiteralPath $zipTemp -Force }

$tarArgs = @(
  '-c', '-a', '-f', $zipTemp,
  '--exclude=node_modules',
  '--exclude=.git',
  '--exclude=dist',
  '--exclude=dist-ssr',
  '--exclude=.cursor',
  "--exclude=$packDirName",
  '-C', $root,
  '.'
)
& tar @tarArgs
if ($LASTEXITCODE -ne 0) { throw "tar failed with exit $LASTEXITCODE" }

Move-Item -LiteralPath $zipTemp -Destination $zipPath -Force

Write-Host "Wrote: $zipPath"
Write-Host "Done. Output folder: $packDir"
